### PR TITLE
Update TodoMVC to Angular 9 and Mobx 3.1.1, enable Redux devtools (#114)

### PR DESCRIPTION
**Pull request by kubk**
Related issue: #114 
Summary of changes:
- Update TodoMVC example to Angular 9 and Mobx 3.1.1
- Enable Redux devtools
- Use CSS from `todomvc-common` and `todomvc-app-css` packages.

image

### CODE REVIEW

**Comment by adamkleingit** [comment]
Thanks!
Unfortunately, I updated the entire project's structure to use Angular CLI, so this will be a very difficult merge.
@kubk can you branch again from master and re-apply your changes - it will probably take less time

**Comment by kubk** [comment]
@adamkleingit Sure, in which folder should I put an updated example? Currently there are 2 folders with examples in master:
- https://github.com/mobxjs/mobx-angular/tree/master/example
- https://github.com/mobxjs/mobx-angular/tree/master/projects

**Comment by kubk** [comment]
@adamkleingit Done, currently there is a folder with 3 examples (todo, bank, tictactoe) and a folder with mobx-angular sources (projects/mobx-angular)

**Comment by adamkleingit** [comment]
@kubk I just removed example, and moved all examples to projects as Angular 9 projects

**Comment by kubk** [comment]
@adamkleingit I've moved the example to the projects folder.

**Comment by adamkleingit** [comment]
I changed back to use the top Workspace angular.json, to make everything work the same way, and to have the app take the local mobx-angular and not from node_modules (if it's built)

**Pull request merged**
