### PR TITLE
chore: update mobx-angular peerDependencies

### PR DESCRIPTION
**Pull request by theoklitosBam7**
Update mobx-angular peerDependencies for Angular 13

### CODE REVIEW

**Comment by floinay** [comment]
+ update please

**Comment by mannysingh6** [comment]
Could we get this PR merged? Thanks

**Comment by jonathan-mcewan** [comment]
Keen for this to be merged as soon as possible. `npm install --force` is not a good solution long term (but will work for you).

**Comment by simonto-tr** [comment]
@SimonTouitou

**Comment by SimonTouitou** [comment]
@theoklitosBam7 @floinay @mannysingh6 @jonathan-mcewan 
Tested locally.
Approved.
You can use github url in the meantime for this change.
I'll publish this merge tomorrow hopefully.

**Pull request merged**
