### PR TITLE
Angular 15 support

### PR DESCRIPTION
**Pull request by modus-jose**
@EVASIVE can you help me test, projects that upgrade are blocked by enforcing peer dependencies

### CODE REVIEW

**Comment by SimonTouitou** [comment]
@modus-jose Thank you for your PR.
I'll have a look at it.

**Comment by Whylandos** [comment]
please add angular 15 support
npm ERR! peer @angular/common@">=11.1.1 <15.0.0" from mobx-angular@4.6.0
npm ERR! node_modules/mobx-angular
npm ERR!   mobx-angular@"4.6.0" from the root project

**Comment by kaemmi84** [comment]
I also need angular 15 support.

**Comment by Mas2112** [comment]
I have tested mobx-angular on Angular 15 with my fairly large project. So far our E2E tests and our manual tests have not found any issues. Can we get this PR merged?

**Comment by SimonTouitou** [comment]
Merged.
I will publish it later today/tomorrow.

**Comment by michermd** [comment]
Hello @SimonTouitou any update?

**Comment by michermd** [comment]
Hello @SimonTouitou can you provide a timeframe for the publication?

**Comment by Chuckv01** [comment]
This version has been published to npm.

**Comment by Whylandos** [comment]
Thank you.

It does not seem to work, sadly.

Angular 15 & different node / npm versions I tried.

Cannot find module 'mobx-angular' or its corresponding type declarations.

**Comment by modus-jose** [comment]
@Whylandos that error seems to be from a different issue. do you have a minimum reproducible repo?

**Comment by Chuckv01** [comment]
🤦 Sorry folks - didn't run `npm publish` from the `dist` directory. `4.7.1` should fix that issue.

**Comment by Whylandos** [comment]
it works

thanks a lot

**Pull request merged**
